server:
  port: ${SB_PORT}
  tomcat:
    basedir: ./tomcat_access_logs/
    accesslog:
      enabled: true
      directory:

spring:
  datasource:
    url: jdbc:mariadb://${DB_IP}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

logging:
  file:
    path: ./spring_logs/
  level:
    root: WARN
    org.hibernate.orm.jdbc.bind: WARN