name: Continuous Integration / Continuous Deployment

concurrency:
  group: production
  cancel-in-progress: true

# invoking condition
on:
  pull_request: # when pull request is invoked, and it closed.
    branches: [ "main" ]
    types: closed
  workflow_dispatch: # trigging in github manually.

    
permissions: # permit only reading the source code in repository.
  contents: read

jobs:
  # Build SpringBoot Application.
  build-docker-image:
    runs-on: 50th_backend
    steps: # Grouping the step of running.
    - uses: actions/checkout@v3
    # 1.
    - name: Install JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    # 2.
    - name: Grant execute permission for gradlew using chmod +x
      run: chmod +x ./gradlew

    # 3.
    - name: Build with Gradle
      run: ./gradlew clean build

    # 4.
    - name: docker image build
      run: docker build -t knu_cse_sdd/web_50th_backend .

  run-docker-image:
    needs: build-docker-image
    runs-on: 50th_backend

    steps:
      - name: halt container
        run: docker stop web_50th_backend 2>/dev/null || true

      - name: run container using Docker-Compose
        run: docker compose -f ../../../../.web-docker-compose-setup.yml up -d web_50th_backend

      - name: remove old image
        run: docker system prune -f